### ISSUE TITLE
Failed to rendering the metadrive environment

### ISSUE THREAD

**Issue by guanjiayi** [liuzuxin/DSRL#7]
I encountered an error when using `env.render()` to render the MetaDrive environment. Have you successfully visualized the 9 environments in DSRL before? If so, could you provide the versions of Panda and Panda3D you used?

Error message:
 ```
Traceback (most recent call last):
 File "make_envs.py", line 12, in <module>
    env.render()
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 51, in render
    return self.env.render(*args, **kwargs)
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 53, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 316, in env_render_passive_checker
    result = env.render(*args, **kwargs)
  File "/home/tjispc_rl/opt/metadrive_clean/metadrive/envs/base_env.py", line 305, in render
    assert self.config["use_render"] or self.engine.mode != RENDER_MODE_NONE, \
AssertionError: Panda Renderring is off now, can not render
```

**Comment by HenryLHH** [comment]
Hi @guanjiayi, the panda3d version we are using is 1.10.8, you may find our MetaDrive version (adopted from v0.2.6.0) in [this repo](https://github.com/HenryLHH/metadrive_clean/).

**Comment by guanjiayi** [comment]
Thank you very much for HenryLHH's reply. We have tried the following but the problem still persists:

- We changed the version of Panda3d to 1.10.8, but the issue was not resolved.

- We followed your instructions, recreated a project, and only installed metadrive_clean v0.2.6.0. When we tested the rendering program, the problem still exists. Could you provide a visual example using version v0.2.6.0?

```
import gym
# import fsrl_metadrive
import metadrive.fsrl_metadrive

env = gym.make("SafeMetaDrive-easysparse-v0")
print(env.action_space)
env.reset()
for i in range(1000): 
    o, r, term, trunc, i = env.step(env.action_space.sample())
    env.render()
    print(r)
env.close()
```

```
Traceback (most recent call last):
  File "examples/make_envs.py", line 12, in <module>
    env.render()
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 51, in render
    return self.env.render(*args, **kwargs)
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 53, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 316, in env_render_passive_checker
    result = env.render(*args, **kwargs)
  File "/home/tjispc_rl/opt/metadrive_clean/metadrive/envs/base_env.py", line 305, in render
    assert self.config["use_render"] or self.engine.mode != RENDER_MODE_NONE, \
AssertionError: Panda Renderring is off now, can not render
```

- [ ] Additionally, we noticed some minor errors in version v0.2.6.0 of metadrive_clean

- The make_env.py header file in the example directory seems to incorrectly use import metadrive.fsrl_metadrive instead of import fsrl_metadrive.

- During the step of installing metadrive_clean, is setup.py missing? Or should the step be `cd FSRL $pip3 install -e .`?

**Comment by guanjiayi** [comment]
- [ ] Thank you very much for HenryLHH's reply. We have tried the following steps, but the problem still persists:

- We changed the version of Panda3d to 1.10.8, but the issue was not resolved.

- We followed your instructions, recreated a project, and only installed metadrive_clean v0.2.6.0. When we tested the rendering program, the problem still exists. Could you provide a visual example for the v0.2.6.0 version?

```
import gym
# import fsrl_metadrive
import metadrive.fsrl_metadrive
import time

env = gym.make("SafeMetaDrive-easysparse-v0")
print(env.action_space)
env.reset()
for i in range(1000): 
    o, r, term, trunc, i = env.step(env.action_space.sample())
    time.sleep(1)
    env.render()
    print(r)
env.close()
```

```
Traceback (most recent call last):
  File "examples/make_envs.py", line 12, in <module>
    env.render()
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 51, in render
    return self.env.render(*args, **kwargs)
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 53, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/home/tjispc_rl/anaconda3/envs/metadrive/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 316, in env_render_passive_checker
    result = env.render(*args, **kwargs)
  File "/home/tjispc_rl/opt/metadrive_clean/metadrive/envs/base_env.py", line 305, in render
    assert self.config["use_render"] or self.engine.mode != RENDER_MODE_NONE, \
AssertionError: Panda Renderring is off now, can not render
```

- [ ] Additionally, we noticed some minor errors in the v0.2.6.0 version:

- In the example directory, the make_env.py header file seems to need to import metadrive.fsrl_metadrive instead of import fsrl_metadrive.

- During the step of installing metadrive_clean, is the setup.py missing? Or should the step be` cd FSRL $pip3 install -e` .

**Comment by HenryLHH** [comment]
Hi @guanjiayi, thank you for raising the issue, we provide a detailed [example script](https://github.com/liuzuxin/DSRL/blob/325980fb08a7c0bd36483f8f13a2ca6da57b11a9/examples/run_metadrive.py#L32) which now support modifying the config of Metadrive env. 

Besides, for the third-person view rendering part, our original dirty version of Metadrive simulator misses a few logo assets, so we also update the [metadrive_clean](https://github.com/HenryLHH/metadrive_clean/) repo. You can simply re-run the following command in the DSRL repo to fix the third-person view rendering bug:  
```bash
pip3 install -e .[metadrive]
```
